dist: trusty
language: rust
services: docker
rust:
  - stable
sudo: required
env:
  global:
    - NAME=udrs

matrix:
  include:
    - env: TARGET=x86_64-unknown-linux-musl
    - env: TARGET=x86_64-apple-darwin
      os: osx
    - env: TARGET=x86_64-pc-windows-gnu

before_install:
  - rustup self update

install:
  - source ~/.cargo/env
  - cargo install --force cross

script:
  - cross test --target $TARGET --release

before_deploy:
  - cross build --target $TARGET --release
  - bin=$NAME
  - if [[ $TARGET = "x86_64-pc-windows-gnu" ]]; then bin=$NAME.exe; fi
  - tar czf $NAME-$TRAVIS_TAG-$TARGET.tar.gz -C target/$TARGET/release $bin

deploy:
  api_key:
    secure: "A57+3kFr5MywkEGBDIHtQ6jsgjHoNVi1K9+wu6YfEH3Ts+ABbjmkQaL9pcMybetk0M2B7FO+tDjEFM7/LKPqvqbtif74W7DZIbc120k1Kpokw23LRKv3McZu7H/fYuLYJ9Ak87I3ZBThrVyldIn5nc5grlTzaW/OkBRDlcWA4Y4u4nuPPyxyJy2cLo+kEQqWOo7lKdwL+fSzbbjT8B8ug5QbhY1bZL77xBVd2zNCSJ8Ss9tlSR7e0rtvzxZa5frhE5/MWTymcZC2KP66CxLZ6Cu4rjJtk6gdq/lPtY9S8wkkjl8E/+hf2L/BpixFP4Db8HMsKSLlNXnxNLc7xNWuofzaiI3hwwVIUgEBTdl3lCBj/Un/selAMtwbXeDe2cky5yBTj8bt9lLBI9A0gGWeNWujt2fpX80u5oDvAb9JnFxn4/XrJKs2OiNujnfAqEoxtSmUFMTFv2P8vdDdXWEI5YW8blT0nfklVQmlGky7EE1jIvQWwJAvRqqc6OYELc6nlJE/v8kTsWmtlPF0guRSbPF5rxXC1/iEc1rUouxGF+kU+yZ/GuhYx9r27Mg5JUyZiJvxdKQJ5b2mX7Tm1l0WyGmpfekb85xz00cuEhyEhCiJTXupzl11UKr7Z8W3+lgu0tWmsGOdTTOkUVVPCNhnClCOvZbjKn0fXMJ9B06Ehbs="
  file_glob: true
  file: $NAME-$TRAVIS_TAG-$TARGET.*
  on:
    tags: true
  provider: releases
  skip_cleanup: true

cache: cargo
before_cache:
  - chmod -R a+r $HOME/.cargo

branches:
  only:
    - /^v?\d+\.\d+\.\d+.*$/
    - master
