# Based on the "trust" template v0.1.2
# https://github.com/japaric/trust/tree/v0.1.2

dist: trusty
language: rust
services: docker
rust:
  - stable
sudo: required
env:
  global:
    # CLIの名前を定義
    - NAME=udrs

# LinuxとmacOSとWindowsの環境でビルドする
matrix:
  include:
    - env: TARGET=x86_64-unknown-linux-musl
    - env: TARGET=x86_64-apple-darwin
      os: osx
    - env: TARGET=x86_64-pc-windows-gnu

before_install:
  # ビルドツールをインストールする前にRustのツールチェインを最新版に更新
  - rustup self update

install:
  # crossツールのインストール
  - source ~/.cargo/env
  - cargo install --force cross

script:
  # cacheが有効になるようにリリースビルドでテストを実行
  - cross test --target $TARGET --release

before_deploy:
  # リリースビルドを実行
  - cross build --target $TARGET --release
  - bin=$NAME
  # Windowsのみ拡張子のexeがバイナリネームに含まれる
  - if [[ $TARGET = "x86_64-pc-windows-gnu" ]]; then bin=$NAME.exe; fi
  # ソースディレクトリ直下に配布用のパッケージを作成
  - tar czf $NAME-$TRAVIS_TAG-$TARGET.tar.gz -C target/$TARGET/release $bin

deploy:
  api_key:
    # `https://travis-ci.com`でアカウントを作成して、Travis CI のGithub Appを対象リポジトリにインストール
    # `https://github.com/settings/tokens/new` でGithubのPersonalAccessTokenを生成
    # gem install travis -v 1.8.9 --no-rdoc --no-ri
    # travis login --com
    # travis encrypt --com {PersonalAccessToken}
    # （Github Appの権限でやってくれればいいのに・・・）
    secure: "..."
  file_glob: true
  file: $NAME-$TRAVIS_TAG-$TARGET.*
  on:
    tags: true
  provider: releases
  skip_cleanup: true

cache: cargo
before_cache:
  - chmod -R a+r $HOME/.cargo

branches:
  only:
    # for release tags
    - /^v?\d+\.\d+\.\d+.*$/
    - master
