[package]
name = "udrs"
version = "0.1.7"
authors = ["syui <syui@syui.cf>"]
edition = "2018"

[dependencies]
url = "1.7"
pretty_env_logger = "0.2"
base64 = "0.9.2"
seahorse = "1.0.0"
dns-lookup = "1.0.2"
